// @generated by protoc-gen-cosmes v0.0.1 with parameter "target=ts"
// @generated from file ibc/applications/perm/v1/query.proto (package ibc.applications.perm.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { QueryChannelRelayerRequest, QueryChannelRelayerResponse } from "./query_pb.js";

const TYPE_NAME = "ibc.applications.perm.v1.Query";

/**
 * ChannelRelayer queries a permissioned ibc relayer for the specific channel.
 *
 * @generated from rpc ibc.applications.perm.v1.Query.ChannelRelayer
 */
export const QueryChannelRelayerService = {
  typeName: TYPE_NAME,
  method: "ChannelRelayer",
  Request: QueryChannelRelayerRequest,
  Response: QueryChannelRelayerResponse,
} as const;

