// @generated by protoc-gen-cosmes v0.0.1 with parameter "target=ts"
// @generated from file ibc/applications/perm/v1/tx.proto (package ibc.applications.perm.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MsgUpdateChannelRelayer, MsgUpdateChannelRelayerResponse } from "./tx_pb.js";

const TYPE_NAME = "ibc.applications.perm.v1.Msg";

/**
 * UpdateChannelRelayer defines a rpc handler method for MsgUpdateChannelRelayer.
 *
 * @generated from rpc ibc.applications.perm.v1.Msg.UpdateChannelRelayer
 */
export const MsgUpdateChannelRelayerService = {
  typeName: TYPE_NAME,
  method: "UpdateChannelRelayer",
  Request: MsgUpdateChannelRelayer,
  Response: MsgUpdateChannelRelayerResponse,
} as const;

