// @generated by protoc-gen-es v1.7.0 with parameter "target=ts"
// @generated from file initia/move/v1/auth.proto (package initia.move.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { BaseAccount } from "../../../cosmos/auth/v1beta1/auth_pb.js";

/**
 * ObjectAccount defines an account for objects that holds coins without pubkey.
 *
 * @generated from message initia.move.v1.ObjectAccount
 */
export class ObjectAccount extends Message<ObjectAccount> {
  /**
   * @generated from field: cosmos.auth.v1beta1.BaseAccount base_account = 1;
   */
  baseAccount?: BaseAccount;

  constructor(data?: PartialMessage<ObjectAccount>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "initia.move.v1.ObjectAccount";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "base_account", kind: "message", T: BaseAccount },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ObjectAccount {
    return new ObjectAccount().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ObjectAccount {
    return new ObjectAccount().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ObjectAccount {
    return new ObjectAccount().fromJsonString(jsonString, options);
  }

  static equals(a: ObjectAccount | PlainMessage<ObjectAccount> | undefined, b: ObjectAccount | PlainMessage<ObjectAccount> | undefined): boolean {
    return proto3.util.equals(ObjectAccount, a, b);
  }
}

/**
 * TableAccount defines an account for tables that holds items without pubkey.
 *
 * @generated from message initia.move.v1.TableAccount
 */
export class TableAccount extends Message<TableAccount> {
  /**
   * @generated from field: cosmos.auth.v1beta1.BaseAccount base_account = 1;
   */
  baseAccount?: BaseAccount;

  constructor(data?: PartialMessage<TableAccount>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "initia.move.v1.TableAccount";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "base_account", kind: "message", T: BaseAccount },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TableAccount {
    return new TableAccount().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TableAccount {
    return new TableAccount().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TableAccount {
    return new TableAccount().fromJsonString(jsonString, options);
  }

  static equals(a: TableAccount | PlainMessage<TableAccount> | undefined, b: TableAccount | PlainMessage<TableAccount> | undefined): boolean {
    return proto3.util.equals(TableAccount, a, b);
  }
}

