// @generated by protoc-gen-cosmes v0.0.1 with parameter "target=ts"
// @generated from file opinit/ophost/v1/tx.proto (package opinit.ophost.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MsgCreateBridge, MsgCreateBridgeResponse, MsgDeleteOutput, MsgDeleteOutputResponse, MsgFinalizeTokenWithdrawal, MsgFinalizeTokenWithdrawalResponse, MsgInitiateTokenDeposit, MsgInitiateTokenDepositResponse, MsgProposeOutput, MsgProposeOutputResponse, MsgRecordBatch, MsgRecordBatchResponse, MsgUpdateChallenger, MsgUpdateChallengerResponse, MsgUpdateParams, MsgUpdateParamsResponse, MsgUpdateProposer, MsgUpdateProposerResponse } from "./tx_pb.js";

const TYPE_NAME = "opinit.ophost.v1.Msg";

/**
 * RecordBatch defines a rpc handler method for MsgRecordBatch.
 *
 * @generated from rpc opinit.ophost.v1.Msg.RecordBatch
 */
export const MsgRecordBatchService = {
  typeName: TYPE_NAME,
  method: "RecordBatch",
  Request: MsgRecordBatch,
  Response: MsgRecordBatchResponse,
} as const;

/**
 * CreateBridge defines a rpc handler method for MsgCreateBridge.
 *
 * @generated from rpc opinit.ophost.v1.Msg.CreateBridge
 */
export const MsgCreateBridgeService = {
  typeName: TYPE_NAME,
  method: "CreateBridge",
  Request: MsgCreateBridge,
  Response: MsgCreateBridgeResponse,
} as const;

/**
 * ProposeOutput defines a rpc handler method for MsgProposeOutput.
 *
 * @generated from rpc opinit.ophost.v1.Msg.ProposeOutput
 */
export const MsgProposeOutputService = {
  typeName: TYPE_NAME,
  method: "ProposeOutput",
  Request: MsgProposeOutput,
  Response: MsgProposeOutputResponse,
} as const;

/**
 * DeleteOutput defines a rpc handler method for MsgDeleteOutput.
 *
 * @generated from rpc opinit.ophost.v1.Msg.DeleteOutput
 */
export const MsgDeleteOutputService = {
  typeName: TYPE_NAME,
  method: "DeleteOutput",
  Request: MsgDeleteOutput,
  Response: MsgDeleteOutputResponse,
} as const;

/**
 * InitiateTokenDeposit defines a user facing l1 => l2 token transfer interface.
 *
 * @generated from rpc opinit.ophost.v1.Msg.InitiateTokenDeposit
 */
export const MsgInitiateTokenDepositService = {
  typeName: TYPE_NAME,
  method: "InitiateTokenDeposit",
  Request: MsgInitiateTokenDeposit,
  Response: MsgInitiateTokenDepositResponse,
} as const;

/**
 * FinalizeTokenWithdrawal defines a user facing l2 => l1 token transfer interface.
 *
 * @generated from rpc opinit.ophost.v1.Msg.FinalizeTokenWithdrawal
 */
export const MsgFinalizeTokenWithdrawalService = {
  typeName: TYPE_NAME,
  method: "FinalizeTokenWithdrawal",
  Request: MsgFinalizeTokenWithdrawal,
  Response: MsgFinalizeTokenWithdrawalResponse,
} as const;

/**
 * UpdateProposer defines a rpc handler method for MsgUpdateProposer.
 *
 * @generated from rpc opinit.ophost.v1.Msg.UpdateProposer
 */
export const MsgUpdateProposerService = {
  typeName: TYPE_NAME,
  method: "UpdateProposer",
  Request: MsgUpdateProposer,
  Response: MsgUpdateProposerResponse,
} as const;

/**
 * UpdateChallenger defines a rpc handler method for MsgUpdateChallenger.
 *
 * @generated from rpc opinit.ophost.v1.Msg.UpdateChallenger
 */
export const MsgUpdateChallengerService = {
  typeName: TYPE_NAME,
  method: "UpdateChallenger",
  Request: MsgUpdateChallenger,
  Response: MsgUpdateChallengerResponse,
} as const;

/**
 * UpdateParams defines an operation for updating the
 * x/opchild module parameters.
 *
 * @generated from rpc opinit.ophost.v1.Msg.UpdateParams
 */
export const MsgUpdateParamsService = {
  typeName: TYPE_NAME,
  method: "UpdateParams",
  Request: MsgUpdateParams,
  Response: MsgUpdateParamsResponse,
} as const;

