// @generated by protoc-gen-es v1.7.0 with parameter "target=ts"
// @generated from file initia/reward/v1/genesis.proto (package initia.reward.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, Timestamp } from "@bufbuild/protobuf";
import { Params } from "./types_pb.js";

/**
 * GenesisState defines the mint module's genesis state.
 *
 * @generated from message initia.reward.v1.GenesisState
 */
export class GenesisState extends Message<GenesisState> {
  /**
   * Params defines all the paramaters of the module.
   *
   * @generated from field: initia.reward.v1.Params params = 1;
   */
  params?: Params;

  /**
   * @generated from field: google.protobuf.Timestamp last_release_timestamp = 2;
   */
  lastReleaseTimestamp?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp last_dilution_timestamp = 3;
   */
  lastDilutionTimestamp?: Timestamp;

  constructor(data?: PartialMessage<GenesisState>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "initia.reward.v1.GenesisState";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "params", kind: "message", T: Params },
    { no: 2, name: "last_release_timestamp", kind: "message", T: Timestamp },
    { no: 3, name: "last_dilution_timestamp", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GenesisState {
    return new GenesisState().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GenesisState {
    return new GenesisState().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GenesisState {
    return new GenesisState().fromJsonString(jsonString, options);
  }

  static equals(a: GenesisState | PlainMessage<GenesisState> | undefined, b: GenesisState | PlainMessage<GenesisState> | undefined): boolean {
    return proto3.util.equals(GenesisState, a, b);
  }
}

