// @generated by protoc-gen-es v1.7.0 with parameter "target=ts"
// @generated from file initia/reward/v1/types.proto (package initia.reward.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Duration, Message, proto3 } from "@bufbuild/protobuf";

/**
 * Params defines the set of mint parameters.
 *
 * @generated from message initia.reward.v1.Params
 */
export class Params extends Message<Params> {
  /**
   * @generated from field: string reward_denom = 1;
   */
  rewardDenom = "";

  /**
   * @generated from field: google.protobuf.Duration dilution_period = 2;
   */
  dilutionPeriod?: Duration;

  /**
   * @generated from field: string release_rate = 3;
   */
  releaseRate = "";

  /**
   * The dilution rate of release rate.
   * if `(block.timestamp - last_dilute_timestamp) < dilution_period`:
   *    `release_rate -= (release_rate * dilution_rate)`
   *    `last_dilution_timestamp = block.timestamp`
   *
   * @generated from field: string dilution_rate = 4;
   */
  dilutionRate = "";

  /**
   * @generated from field: bool release_enabled = 5;
   */
  releaseEnabled = false;

  constructor(data?: PartialMessage<Params>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "initia.reward.v1.Params";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "reward_denom", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "dilution_period", kind: "message", T: Duration },
    { no: 3, name: "release_rate", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "dilution_rate", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "release_enabled", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Params {
    return new Params().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Params {
    return new Params().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Params {
    return new Params().fromJsonString(jsonString, options);
  }

  static equals(a: Params | PlainMessage<Params> | undefined, b: Params | PlainMessage<Params> | undefined): boolean {
    return proto3.util.equals(Params, a, b);
  }
}

