// @generated by protoc-gen-cosmes v0.0.1 with parameter "target=ts"
// @generated from file initia/intertx/v1/query.proto (package initia.intertx.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { QueryInterchainAccountRequest, QueryInterchainAccountResponse } from "./query_pb.js";

const TYPE_NAME = "initia.intertx.v1.Query";

/**
 * QueryInterchainAccount returns the interchain account for given owner address on a given connection pair
 *
 * @generated from rpc initia.intertx.v1.Query.InterchainAccount
 */
export const QueryInterchainAccountService = {
  typeName: TYPE_NAME,
  method: "InterchainAccount",
  Request: QueryInterchainAccountRequest,
  Response: QueryInterchainAccountResponse,
} as const;

