// @generated by protoc-gen-cosmes v0.0.1 with parameter "target=ts"
// @generated from file initia/intertx/v1/tx.proto (package initia.intertx.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MsgRegisterAccount, MsgRegisterAccountResponse, MsgSubmitTx, MsgSubmitTxResponse } from "./tx_pb.js";

const TYPE_NAME = "initia.intertx.v1.Msg";

/**
 * Register defines a rpc handler for MsgRegisterAccount
 *
 * @generated from rpc initia.intertx.v1.Msg.RegisterAccount
 */
export const MsgRegisterAccountService = {
  typeName: TYPE_NAME,
  method: "RegisterAccount",
  Request: MsgRegisterAccount,
  Response: MsgRegisterAccountResponse,
} as const;

/**
 * SubmitTx defines a rpc handler for MsgSubmitTx
 *
 * @generated from rpc initia.intertx.v1.Msg.SubmitTx
 */
export const MsgSubmitTxService = {
  typeName: TYPE_NAME,
  method: "SubmitTx",
  Request: MsgSubmitTx,
  Response: MsgSubmitTxResponse,
} as const;

