// @generated by protoc-gen-cosmes v0.0.1 with parameter "target=ts"
// @generated from file opinit/opchild/v1/query.proto (package opinit.opchild.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { QueryParamsRequest, QueryParamsResponse, QueryValidatorRequest, QueryValidatorResponse, QueryValidatorsRequest, QueryValidatorsResponse } from "./query_pb.js";

const TYPE_NAME = "opinit.opchild.v1.Query";

/**
 * Validators queries all validators
 *
 * When called from another module, this query might consume a high amount of
 * gas if the pagination field is incorrectly set.
 *
 * @generated from rpc opinit.opchild.v1.Query.Validators
 */
export const QueryValidatorsService = {
  typeName: TYPE_NAME,
  method: "Validators",
  Request: QueryValidatorsRequest,
  Response: QueryValidatorsResponse,
} as const;

/**
 * Validator queries validator info for given validator address.
 *
 * @generated from rpc opinit.opchild.v1.Query.Validator
 */
export const QueryValidatorService = {
  typeName: TYPE_NAME,
  method: "Validator",
  Request: QueryValidatorRequest,
  Response: QueryValidatorResponse,
} as const;

/**
 * Parameters queries the rollup parameters.
 *
 * @generated from rpc opinit.opchild.v1.Query.Params
 */
export const QueryParamsService = {
  typeName: TYPE_NAME,
  method: "Params",
  Request: QueryParamsRequest,
  Response: QueryParamsResponse,
} as const;

