// @generated by protoc-gen-es v1.7.0 with parameter "target=ts"
// @generated from file ibc/applications/fetchprice/genesis/v1/genesis.proto (package ibc.applications.fetchprice.genesis.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { GenesisState as GenesisState$1 } from "../../consumer/v1/genesis_pb.js";
import { GenesisState as GenesisState$2 } from "../../provider/v1/genesis_pb.js";

/**
 * GenesisState defines the ibc fetch-price genesis state
 *
 * @generated from message ibc.applications.fetchprice.genesis.v1.GenesisState
 */
export class GenesisState extends Message<GenesisState> {
  /**
   * @generated from field: ibc.applications.fetchprice.consumer.v1.GenesisState consumer_genesis_state = 1;
   */
  consumerGenesisState?: GenesisState$1;

  /**
   * @generated from field: ibc.applications.fetchprice.provider.v1.GenesisState provider_genesis_state = 2;
   */
  providerGenesisState?: GenesisState$2;

  constructor(data?: PartialMessage<GenesisState>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ibc.applications.fetchprice.genesis.v1.GenesisState";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "consumer_genesis_state", kind: "message", T: GenesisState$1 },
    { no: 2, name: "provider_genesis_state", kind: "message", T: GenesisState$2 },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GenesisState {
    return new GenesisState().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GenesisState {
    return new GenesisState().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GenesisState {
    return new GenesisState().fromJsonString(jsonString, options);
  }

  static equals(a: GenesisState | PlainMessage<GenesisState> | undefined, b: GenesisState | PlainMessage<GenesisState> | undefined): boolean {
    return proto3.util.equals(GenesisState, a, b);
  }
}

