// @generated by protoc-gen-cosmes v0.0.1 with parameter "target=ts"
// @generated from file initia/mstaking/v1/tx.proto (package initia.mstaking.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MsgBeginRedelegate, MsgBeginRedelegateResponse, MsgCancelUnbondingDelegation, MsgCancelUnbondingDelegationResponse, MsgCreateValidator, MsgCreateValidatorResponse, MsgDelegate, MsgDelegateResponse, MsgEditValidator, MsgEditValidatorResponse, MsgUndelegate, MsgUndelegateResponse, MsgUpdateParams, MsgUpdateParamsResponse } from "./tx_pb.js";

const TYPE_NAME = "initia.mstaking.v1.Msg";

/**
 * CreateValidator defines a method for creating a new validator.
 *
 * @generated from rpc initia.mstaking.v1.Msg.CreateValidator
 */
export const MsgCreateValidatorService = {
  typeName: TYPE_NAME,
  method: "CreateValidator",
  Request: MsgCreateValidator,
  Response: MsgCreateValidatorResponse,
} as const;

/**
 * EditValidator defines a method for editing an existing validator.
 *
 * @generated from rpc initia.mstaking.v1.Msg.EditValidator
 */
export const MsgEditValidatorService = {
  typeName: TYPE_NAME,
  method: "EditValidator",
  Request: MsgEditValidator,
  Response: MsgEditValidatorResponse,
} as const;

/**
 * Delegate defines a method for performing a delegation of coins
 * from a delegator to a validator.
 *
 * @generated from rpc initia.mstaking.v1.Msg.Delegate
 */
export const MsgDelegateService = {
  typeName: TYPE_NAME,
  method: "Delegate",
  Request: MsgDelegate,
  Response: MsgDelegateResponse,
} as const;

/**
 * BeginRedelegate defines a method for performing a redelegation
 * of coins from a delegator and source validator to a destination validator.
 *
 * @generated from rpc initia.mstaking.v1.Msg.BeginRedelegate
 */
export const MsgBeginRedelegateService = {
  typeName: TYPE_NAME,
  method: "BeginRedelegate",
  Request: MsgBeginRedelegate,
  Response: MsgBeginRedelegateResponse,
} as const;

/**
 * Undelegate defines a method for performing an undelegation from a
 * delegate and a validator.
 *
 * @generated from rpc initia.mstaking.v1.Msg.Undelegate
 */
export const MsgUndelegateService = {
  typeName: TYPE_NAME,
  method: "Undelegate",
  Request: MsgUndelegate,
  Response: MsgUndelegateResponse,
} as const;

/**
 * CancelUnbondingDelegation defines a method for performing canceling the unbonding delegation
 * and delegate back to previous validator.
 *
 * @generated from rpc initia.mstaking.v1.Msg.CancelUnbondingDelegation
 */
export const MsgCancelUnbondingDelegationService = {
  typeName: TYPE_NAME,
  method: "CancelUnbondingDelegation",
  Request: MsgCancelUnbondingDelegation,
  Response: MsgCancelUnbondingDelegationResponse,
} as const;

/**
 * UpdateParams defines an operation for updating the x/staking module
 * parameters.
 *
 * @generated from rpc initia.mstaking.v1.Msg.UpdateParams
 */
export const MsgUpdateParamsService = {
  typeName: TYPE_NAME,
  method: "UpdateParams",
  Request: MsgUpdateParams,
  Response: MsgUpdateParamsResponse,
} as const;

