// @generated by protoc-gen-cosmes v0.0.1 with parameter "target=ts"
// @generated from file initia/distribution/v1/query.proto (package initia.distribution.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { QueryDelegationRewardsRequest, QueryDelegationRewardsResponse, QueryDelegationTotalRewardsRequest, QueryDelegationTotalRewardsResponse, QueryParamsRequest, QueryParamsResponse, QueryValidatorCommissionRequest, QueryValidatorCommissionResponse, QueryValidatorOutstandingRewardsRequest, QueryValidatorOutstandingRewardsResponse, QueryValidatorSlashesRequest, QueryValidatorSlashesResponse } from "./query_pb.js";

const TYPE_NAME = "initia.distribution.v1.Query";

/**
 * Params queries params of the distribution module.
 *
 * @generated from rpc initia.distribution.v1.Query.Params
 */
export const QueryParamsService = {
  typeName: TYPE_NAME,
  method: "Params",
  Request: QueryParamsRequest,
  Response: QueryParamsResponse,
} as const;

/**
 * ValidatorOutstandingRewards queries rewards of a validator address.
 *
 * @generated from rpc initia.distribution.v1.Query.ValidatorOutstandingRewards
 */
export const QueryValidatorOutstandingRewardsService = {
  typeName: TYPE_NAME,
  method: "ValidatorOutstandingRewards",
  Request: QueryValidatorOutstandingRewardsRequest,
  Response: QueryValidatorOutstandingRewardsResponse,
} as const;

/**
 * ValidatorCommission queries accumulated commission for a validator.
 *
 * @generated from rpc initia.distribution.v1.Query.ValidatorCommission
 */
export const QueryValidatorCommissionService = {
  typeName: TYPE_NAME,
  method: "ValidatorCommission",
  Request: QueryValidatorCommissionRequest,
  Response: QueryValidatorCommissionResponse,
} as const;

/**
 * ValidatorSlashes queries slash events of a validator.
 *
 * @generated from rpc initia.distribution.v1.Query.ValidatorSlashes
 */
export const QueryValidatorSlashesService = {
  typeName: TYPE_NAME,
  method: "ValidatorSlashes",
  Request: QueryValidatorSlashesRequest,
  Response: QueryValidatorSlashesResponse,
} as const;

/**
 * DelegationRewards queries the total rewards accrued by a delegation.
 *
 * @generated from rpc initia.distribution.v1.Query.DelegationRewards
 */
export const QueryDelegationRewardsService = {
  typeName: TYPE_NAME,
  method: "DelegationRewards",
  Request: QueryDelegationRewardsRequest,
  Response: QueryDelegationRewardsResponse,
} as const;

/**
 * DelegationTotalRewards queries the total rewards accrued by a each
 * validator.
 *
 * @generated from rpc initia.distribution.v1.Query.DelegationTotalRewards
 */
export const QueryDelegationTotalRewardsService = {
  typeName: TYPE_NAME,
  method: "DelegationTotalRewards",
  Request: QueryDelegationTotalRewardsRequest,
  Response: QueryDelegationTotalRewardsResponse,
} as const;

