// @generated by protoc-gen-cosmes v0.0.1 with parameter "target=ts"
// @generated from file initia/distribution/v1/tx.proto (package initia.distribution.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MsgDepositValidatorRewardsPool, MsgDepositValidatorRewardsPoolResponse, MsgUpdateParams, MsgUpdateParamsResponse } from "./tx_pb.js";

const TYPE_NAME = "initia.distribution.v1.Msg";

/**
 * UpdateParams defines a governance operation for updating the x/distribution
 * module parameters. The authority is defined in the keeper.
 *
 * @generated from rpc initia.distribution.v1.Msg.UpdateParams
 */
export const MsgUpdateParamsService = {
  typeName: TYPE_NAME,
  method: "UpdateParams",
  Request: MsgUpdateParams,
  Response: MsgUpdateParamsResponse,
} as const;

/**
 * DepositValidatorRewardsPool defines a method to provide additional rewards
 * to delegators to a specific validator.
 *
 * @generated from rpc initia.distribution.v1.Msg.DepositValidatorRewardsPool
 */
export const MsgDepositValidatorRewardsPoolService = {
  typeName: TYPE_NAME,
  method: "DepositValidatorRewardsPool",
  Request: MsgDepositValidatorRewardsPool,
  Response: MsgDepositValidatorRewardsPoolResponse,
} as const;

