// @generated by protoc-gen-cosmes v0.0.1 with parameter "target=ts"
// @generated from file initia/gov/v1/query.proto (package initia.gov.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { QueryEmergencyProposalsRequest, QueryEmergencyProposalsResponse, QueryParamsRequest, QueryParamsResponse, QueryProposalRequest, QueryProposalResponse, QueryProposalsRequest, QueryProposalsResponse } from "./query_pb.js";

const TYPE_NAME = "initia.gov.v1.Query";

/**
 * Params queries params of the gov module.
 *
 * @generated from rpc initia.gov.v1.Query.Params
 */
export const QueryParamsService = {
  typeName: TYPE_NAME,
  method: "Params",
  Request: QueryParamsRequest,
  Response: QueryParamsResponse,
} as const;

/**
 * EmergencyProposals queries emergency proposals.
 *
 * @generated from rpc initia.gov.v1.Query.EmergencyProposals
 */
export const QueryEmergencyProposalsService = {
  typeName: TYPE_NAME,
  method: "EmergencyProposals",
  Request: QueryEmergencyProposalsRequest,
  Response: QueryEmergencyProposalsResponse,
} as const;

/**
 * Proposal queries proposal details based on ProposalID.
 *
 * @generated from rpc initia.gov.v1.Query.Proposal
 */
export const QueryProposalService = {
  typeName: TYPE_NAME,
  method: "Proposal",
  Request: QueryProposalRequest,
  Response: QueryProposalResponse,
} as const;

/**
 * Proposals queries all proposals based on given status.
 *
 * @generated from rpc initia.gov.v1.Query.Proposals
 */
export const QueryProposalsService = {
  typeName: TYPE_NAME,
  method: "Proposals",
  Request: QueryProposalsRequest,
  Response: QueryProposalsResponse,
} as const;

