// @generated by protoc-gen-cosmes v0.0.1 with parameter "target=ts"
// @generated from file ibc/applications/fetchprice/consumer/v1/query.proto (package ibc.applications.fetchprice.consumer.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { QueryAllPricesRequest, QueryAllPricesResponse, QueryPriceRequest, QueryPriceResponse, QueryPricesRequest, QueryPricesResponse } from "./query_pb.js";

const TYPE_NAME = "ibc.applications.fetchprice.consumer.v1.Query";

/**
 * Price queries a price information.
 *
 * @generated from rpc ibc.applications.fetchprice.consumer.v1.Query.Price
 */
export const QueryPriceService = {
  typeName: TYPE_NAME,
  method: "Price",
  Request: QueryPriceRequest,
  Response: QueryPriceResponse,
} as const;

/**
 * Prices queries prices.
 *
 * @generated from rpc ibc.applications.fetchprice.consumer.v1.Query.Prices
 */
export const QueryPricesService = {
  typeName: TYPE_NAME,
  method: "Prices",
  Request: QueryPricesRequest,
  Response: QueryPricesResponse,
} as const;

/**
 * AllPrices queries all prices.
 *
 * @generated from rpc ibc.applications.fetchprice.consumer.v1.Query.AllPrices
 */
export const QueryAllPricesService = {
  typeName: TYPE_NAME,
  method: "AllPrices",
  Request: QueryAllPricesRequest,
  Response: QueryAllPricesResponse,
} as const;

