// @generated by protoc-gen-cosmes v0.0.1 with parameter "target=ts"
// @generated from file ibc/applications/fetchprice/consumer/v1/tx.proto (package ibc.applications.fetchprice.consumer.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MsgFetchPrice, MsgFetchPriceResponse } from "./tx_pb.js";

const TYPE_NAME = "ibc.applications.fetchprice.consumer.v1.Msg";

/**
 * FetchPrice defines a rpc handler method for MsgFetchPrice.
 *
 * @generated from rpc ibc.applications.fetchprice.consumer.v1.Msg.FetchPrice
 */
export const MsgFetchPriceService = {
  typeName: TYPE_NAME,
  method: "FetchPrice",
  Request: MsgFetchPrice,
  Response: MsgFetchPriceResponse,
} as const;

